from fastapi import FastAPI, UploadFile, File, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
import subprocess
import uuid
import os

app = FastAPI(title="FaceTalk AI - Simplified 3D Backend Server")

# Enable CORS for the React development server
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://127.0.0.1:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure temp directory exists
TEMP_DIR = "temp"
os.makedirs(TEMP_DIR, exist_ok=True)

@app.get("/health")
def health():
    return {"status": "running"}

@app.post("/log-error")
async def log_error(request: Request):
    data = await request.json()
    print("\n[BROWSER RUNTIME ERROR]")
    
    # Safe printing to avoid Windows cp1252 encoding crashes
    def safe_print(text):
        try:
            print(text)
        except UnicodeEncodeError:
            try:
                print(text.encode('ascii', errors='replace').decode('ascii'))
            except Exception:
                pass

    safe_print(f"Message: {data.get('message', 'No message')}")
    safe_print(f"Stack: {data.get('stack', 'No stack trace')}")
    print("----------------------------------------\n")
    return {"status": "logged"}

@app.post("/generate-video")
async def generate_video(
    image: UploadFile = File(...),
    audio: UploadFile = File(...)
):
    try:
        job_id = str(uuid.uuid4())
        image_path = os.path.join(TEMP_DIR, f"{job_id}.png")
        audio_path = os.path.join(TEMP_DIR, f"{job_id}.mp3")
        output_dir = os.path.join(TEMP_DIR, f"{job_id}_out")
        os.makedirs(output_dir, exist_ok=True)
        
        # Save uploaded portrait image
        with open(image_path, "wb") as f:
            f.write(await image.read())
            
        # Save uploaded TTS voice clip
        with open(audio_path, "wb") as f:
            f.write(await audio.read())
        
        # Verify if SadTalker inference script is available
        sadtalker_path = os.path.join("SadTalker", "inference.py")
        if not os.path.exists(sadtalker_path):
            print(f"[Warning] SadTalker script not found. Returning simulation error.")
            return {"error": "SadTalker directory missing or not installed"}
            
        # Run SadTalker inference subprocess
        print(f"Launching SadTalker inference for job {job_id}...")
        result = subprocess.run([
            "python", sadtalker_path,
            "--driven_audio", audio_path,
            "--source_image", image_path,
            "--result_dir", output_dir,
            "--still",
            "--preprocess", "crop"
        ], capture_output=True, text=True)
        
        if result.returncode != 0:
            print("SadTalker Error Output:", result.stderr)
            return {"error": f"SadTalker execution failed: {result.stderr}"}
        
        # Search output directory for generated video mp4 file
        output_files = [f for f in os.listdir(output_dir) if f.endswith('.mp4')]
        if not output_files:
            return {"error": "No MP4 video file generated by SadTalker"}
            
        video_filename = output_files[0]
        video_full_path = os.path.join(output_dir, video_filename)
        
        return FileResponse(
            video_full_path,
            media_type="video/mp4",
            filename=video_filename
        )
        
    except Exception as e:
        print("Internal Server Error:", str(e))
        return {"error": f"Internal Server Error: {str(e)}"}
